apiVersion: batch/v1
kind: ScheduledJob
metadata:
  name: curator
spec:
  schedule: "*/1 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          containers:
          - name: curator
            image: bobrik/curator
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          restartPolicy: OnFailure
