apiVersion: v1
kind: Service
metadata:
  annotations:
    domainName: logs.alpha.etpaf.docker-demos.com
  name: kibana
  namespace: default
  labels:
    component: elk
    role: kibana
    dns: route53
spec:
  type: LoadBalancer
  selector:
    component: elk
    role: kibana
  ports:
  - name: http
    port: 80
    targetPort: 5601
    protocol: TCP
